// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api.proto

/*
Package api is a generated blademaster stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-bm v0.1.

package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

It is generated from these files:
	api.proto
*/
package api

import (
	"context"

	bm "github.com/bilibili/kratos/pkg/net/http/blademaster"
	"github.com/bilibili/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathShortURLShorten = "/api/url/shorten"
var PathShortURLGetRawURL = "/platform.shorturl.v1.ShortURL/GetRawURL"

// ShortURLBMServer is the server API for ShortURL service.
type ShortURLBMServer interface {
	Shorten(ctx context.Context, req *URLReq) (resp *URLResp, err error)

	GetRawURL(ctx context.Context, req *GetRawURLReq) (resp *GetRawURLResp, err error)
}

var ShortURLSvc ShortURLBMServer

func shortURLShorten(c *bm.Context) {
	p := new(URLReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := ShortURLSvc.Shorten(c, p)
	c.JSON(resp, err)
}

func shortURLGetRawURL(c *bm.Context) {
	p := new(GetRawURLReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := ShortURLSvc.GetRawURL(c, p)
	c.JSON(resp, err)
}

// RegisterShortURLBMServer Register the blademaster route
func RegisterShortURLBMServer(e *bm.Engine, server ShortURLBMServer) {
	ShortURLSvc = server
	e.POST("/api/url/shorten", shortURLShorten)
	e.GET("/platform.shorturl.v1.ShortURL/GetRawURL", shortURLGetRawURL)
}
